import { DateTime } from "luxon";
import * as XLSX from "xlsx";

import { downloadBlob } from "./download-blob";
import type { ExportSnapshot } from "./types";

const TAGLINE = "Care for Confidence";

function buildFilename(slug: string, extension: string): string {
  const date = DateTime.utc().toFormat("yyyy-MM-dd");
  return `${slug}-${date}.${extension}`;
}

function formatGeneratedAt(iso: string): string {
  const dt = DateTime.fromISO(iso, { zone: "utc" });
  return dt.isValid ? dt.toFormat("dd LLL yyyy, HH:mm") + " UTC" : iso;
}

export async function exportToExcel(snapshot: ExportSnapshot): Promise<void> {
  const sheetRows: string[][] = [
    ["Cosmediate"],
    [TAGLINE],
    [snapshot.title],
    [`Generated: ${formatGeneratedAt(snapshot.generatedAt)}`],
    [`Exported by: ${snapshot.exportedBy}`],
    ...snapshot.filterLines.map((line) => [line]),
  ];

  if (snapshot.sortLine) {
    sheetRows.push([snapshot.sortLine]);
  }

  sheetRows.push([]);
  sheetRows.push(snapshot.headers);
  sheetRows.push(...snapshot.rows);
  sheetRows.push([]);
  sheetRows.push([
    `Generated by Cosmediate · ${TAGLINE} · ${formatGeneratedAt(snapshot.generatedAt)}`,
  ]);

  const worksheet = XLSX.utils.aoa_to_sheet(sheetRows);
  worksheet["!cols"] = snapshot.headers.map(() => ({ wch: 22 }));

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Export");

  const buffer = XLSX.write(workbook, {
    bookType: "xlsx",
    type: "array",
  });

  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  downloadBlob(blob, buildFilename(snapshot.slug, "xlsx"));
}
