import autoTable from "jspdf-autotable";
import { DateTime } from "luxon";
import { jsPDF } from "jspdf";

import { loadExportLogoDataUrl } from "./load-export-logo";
import { downloadBlob } from "./download-blob";
import type { ExportSnapshot } from "./types";

const TAGLINE = "Care for Confidence";

function buildFilename(slug: string, extension: string): string {
  const date = DateTime.utc().toFormat("yyyy-MM-dd");
  return `${slug}-${date}.${extension}`;
}

function formatGeneratedAt(iso: string): string {
  const dt = DateTime.fromISO(iso, { zone: "utc" });
  return dt.isValid ? dt.toFormat("dd LLL yyyy, HH:mm") + " UTC" : iso;
}

export async function exportToPdf(snapshot: ExportSnapshot): Promise<void> {
  const logoDataUrl = await loadExportLogoDataUrl();
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = margin;

  doc.addImage(logoDataUrl, "PNG", pageWidth / 2 - 40, y, 80, 28);
  y += 36;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(TAGLINE, pageWidth / 2, y, { align: "center" });
  y += 24;

  doc.setFontSize(16);
  doc.setTextColor(20);
  doc.text(snapshot.title, pageWidth / 2, y, { align: "center" });
  y += 20;

  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text(`Generated: ${formatGeneratedAt(snapshot.generatedAt)}`, margin, y);
  doc.text(`Exported by: ${snapshot.exportedBy}`, pageWidth - margin, y, {
    align: "right",
  });
  y += 14;

  for (const line of snapshot.filterLines) {
    doc.text(line, margin, y);
    y += 12;
  }

  if (snapshot.sortLine) {
    doc.text(snapshot.sortLine, margin, y);
    y += 12;
  }

  y += 8;

  autoTable(doc, {
    startY: y,
    head: [snapshot.headers],
    body: snapshot.rows,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 8,
      cellPadding: 4,
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [30, 30, 30],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [252, 252, 252],
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    const footerY = doc.internal.pageSize.getHeight() - 20;
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(
      `Generated by Cosmediate · ${TAGLINE} · ${formatGeneratedAt(snapshot.generatedAt)}`,
      pageWidth / 2,
      footerY,
      { align: "center" },
    );
  }

  const blob = doc.output("blob");
  downloadBlob(blob, buildFilename(snapshot.slug, "pdf"));
}
