/** Default sender when config / env does not override. */
export const DEFAULT_FROM_EMAIL = "hello@cosmediate.com";

/** Default public marketing site (sign-in lives here or on auth subdomain). */
export const DEFAULT_APP_BASE_URL = "https://cosmediate.nl";

/** Default management dashboard app. */
export const DEFAULT_APP_DASHBOARD_URL = "https://app.cosmediate.nl";

/** Default dev alert dedupe window (15 minutes). */
export const DEFAULT_DEV_ALERT_MIN_INTERVAL_MS = 15 * 60 * 1000;

export const EMAIL_CATEGORY = Object.freeze({
  AUTH: "AUTH",
  TRANSACTIONAL: "TRANSACTIONAL",
  DEV: "DEV",
  ADMIN: "ADMIN",
  USER_NOTIFICATION: "USER_NOTIFICATION",
});

/**
 * All email types. Auth types are rendered by cognito-auth-emails (no SES).
 * Transactional types are sent via sendEmail / queueEmail.
 */
export const EMAIL_TYPE = Object.freeze({
  // Cognito Custom Message (render only)
  AUTH_ADMIN_CREATE_USER: "AUTH_ADMIN_CREATE_USER",
  AUTH_SIGN_UP: "AUTH_SIGN_UP",
  AUTH_SIGN_UP_RESEND: "AUTH_SIGN_UP_RESEND",
  AUTH_FORGOT_PASSWORD: "AUTH_FORGOT_PASSWORD",
  AUTH_FORGOT_PASSWORD_RESEND: "AUTH_FORGOT_PASSWORD_RESEND",
  AUTH_VERIFY_USER_ATTRIBUTE: "AUTH_VERIFY_USER_ATTRIBUTE",
  AUTH_UPDATE_USER_ATTRIBUTE: "AUTH_UPDATE_USER_ATTRIBUTE",
  AUTH_AUTHENTICATION: "AUTH_AUTHENTICATION",

  // Transactional (SES)
  WELCOME_PATIENT: "WELCOME_PATIENT",
  WELCOME_SPECIALIST: "WELCOME_SPECIALIST",
  WELCOME_MANAGER: "WELCOME_MANAGER",
  WELCOME_ADMIN: "WELCOME_ADMIN",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  SOCIAL_ACCOUNT_LINKED: "SOCIAL_ACCOUNT_LINKED",

  // Dev / runtime alerts
  DEV_RUNTIME_ERROR: "DEV_RUNTIME_ERROR",
  DEV_DLQ_MESSAGE: "DEV_DLQ_MESSAGE",

  ADMIN_USER_PROVISIONED: "ADMIN_USER_PROVISIONED",
  ADMIN_PERMISSIONS_CHANGED: "ADMIN_PERMISSIONS_CHANGED",
  ADMIN_ENTITY_CREATED: "ADMIN_ENTITY_CREATED",
  ADMIN_ENTITY_UPDATED: "ADMIN_ENTITY_UPDATED",
  ADMIN_ENTITY_DELETED: "ADMIN_ENTITY_DELETED",
  ADMIN_SENSITIVE_ACTION: "ADMIN_SENSITIVE_ACTION",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_ACCOUNT_UPDATED: "USER_ACCOUNT_UPDATED",
  USER_CLINIC_UPDATED: "USER_CLINIC_UPDATED",
  USER_CLINIC_DELETED: "USER_CLINIC_DELETED",
  USER_MANAGER_CLINIC_ASSIGNED: "USER_MANAGER_CLINIC_ASSIGNED",
  USER_MANAGER_CLINIC_REMOVED: "USER_MANAGER_CLINIC_REMOVED",
  USER_MANAGER_DELETED: "USER_MANAGER_DELETED",
  USER_SPECIALIST_CLINIC_ASSIGNED: "USER_SPECIALIST_CLINIC_ASSIGNED",
  USER_SPECIALIST_CLINIC_REMOVED: "USER_SPECIALIST_CLINIC_REMOVED",
  USER_SPECIALIST_UPDATED: "USER_SPECIALIST_UPDATED",
  USER_SPECIALIST_DELETED: "USER_SPECIALIST_DELETED",
  USER_PATIENT_CREATOR_CONFIRM: "USER_PATIENT_CREATOR_CONFIRM",
  USER_PATIENT_DELETED: "USER_PATIENT_DELETED",
  USER_STAFF_ACTION_UPDATED: "USER_STAFF_ACTION_UPDATED",
  USER_STAFF_ACTION_DELETED: "USER_STAFF_ACTION_DELETED",
  USER_TREATMENT_ASSIGNED: "USER_TREATMENT_ASSIGNED",
  USER_TREATMENT_REMOVED: "USER_TREATMENT_REMOVED",
  USER_APPOINTMENT_BOOKED: "USER_APPOINTMENT_BOOKED",
  USER_APPOINTMENT_CANCELLED: "USER_APPOINTMENT_CANCELLED",
  USER_APPOINTMENT_RESCHEDULED: "USER_APPOINTMENT_RESCHEDULED",
  USER_REVIEW_RECEIVED: "USER_REVIEW_RECEIVED",
  USER_REVIEW_REPLY_RECEIVED: "USER_REVIEW_REPLY_RECEIVED",
});

/** @type {Record<string, { category: string, priority?: string, rateLimitKey?: string }>} */
export const EMAIL_TYPE_META = Object.freeze({
  [EMAIL_TYPE.AUTH_ADMIN_CREATE_USER]: { category: EMAIL_CATEGORY.AUTH },
  [EMAIL_TYPE.AUTH_SIGN_UP]: { category: EMAIL_CATEGORY.AUTH },
  [EMAIL_TYPE.AUTH_SIGN_UP_RESEND]: { category: EMAIL_CATEGORY.AUTH },
  [EMAIL_TYPE.AUTH_FORGOT_PASSWORD]: { category: EMAIL_CATEGORY.AUTH },
  [EMAIL_TYPE.AUTH_FORGOT_PASSWORD_RESEND]: { category: EMAIL_CATEGORY.AUTH },
  [EMAIL_TYPE.AUTH_VERIFY_USER_ATTRIBUTE]: { category: EMAIL_CATEGORY.AUTH },
  [EMAIL_TYPE.AUTH_UPDATE_USER_ATTRIBUTE]: { category: EMAIL_CATEGORY.AUTH },
  [EMAIL_TYPE.AUTH_AUTHENTICATION]: { category: EMAIL_CATEGORY.AUTH },

  [EMAIL_TYPE.WELCOME_PATIENT]: { category: EMAIL_CATEGORY.TRANSACTIONAL },
  [EMAIL_TYPE.WELCOME_SPECIALIST]: { category: EMAIL_CATEGORY.TRANSACTIONAL },
  [EMAIL_TYPE.WELCOME_MANAGER]: { category: EMAIL_CATEGORY.TRANSACTIONAL },
  [EMAIL_TYPE.WELCOME_ADMIN]: { category: EMAIL_CATEGORY.TRANSACTIONAL },
  [EMAIL_TYPE.PASSWORD_CHANGED]: { category: EMAIL_CATEGORY.TRANSACTIONAL },
  [EMAIL_TYPE.SOCIAL_ACCOUNT_LINKED]: {
    category: EMAIL_CATEGORY.TRANSACTIONAL,
  },

  [EMAIL_TYPE.DEV_RUNTIME_ERROR]: {
    category: EMAIL_CATEGORY.DEV,
    priority: "high",
    rateLimitKey: "dev-runtime",
  },
  [EMAIL_TYPE.DEV_DLQ_MESSAGE]: {
    category: EMAIL_CATEGORY.DEV,
    priority: "high",
    rateLimitKey: "dev-dlq",
  },

  [EMAIL_TYPE.ADMIN_USER_PROVISIONED]: { category: EMAIL_CATEGORY.ADMIN },
  [EMAIL_TYPE.ADMIN_PERMISSIONS_CHANGED]: { category: EMAIL_CATEGORY.ADMIN },
  [EMAIL_TYPE.ADMIN_ENTITY_CREATED]: { category: EMAIL_CATEGORY.ADMIN },
  [EMAIL_TYPE.ADMIN_ENTITY_UPDATED]: { category: EMAIL_CATEGORY.ADMIN },
  [EMAIL_TYPE.ADMIN_ENTITY_DELETED]: { category: EMAIL_CATEGORY.ADMIN },
  [EMAIL_TYPE.ADMIN_SENSITIVE_ACTION]: { category: EMAIL_CATEGORY.ADMIN },

  [EMAIL_TYPE.USER_PROFILE_UPDATED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_ACCOUNT_UPDATED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_CLINIC_UPDATED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_CLINIC_DELETED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_MANAGER_CLINIC_ASSIGNED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_MANAGER_CLINIC_REMOVED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_MANAGER_DELETED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_SPECIALIST_CLINIC_ASSIGNED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_SPECIALIST_CLINIC_REMOVED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_SPECIALIST_UPDATED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_SPECIALIST_DELETED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_PATIENT_CREATOR_CONFIRM]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_PATIENT_DELETED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_STAFF_ACTION_UPDATED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_STAFF_ACTION_DELETED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_TREATMENT_ASSIGNED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_TREATMENT_REMOVED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_APPOINTMENT_BOOKED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_APPOINTMENT_CANCELLED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_APPOINTMENT_RESCHEDULED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_REVIEW_RECEIVED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
  [EMAIL_TYPE.USER_REVIEW_REPLY_RECEIVED]: {
    category: EMAIL_CATEGORY.USER_NOTIFICATION,
  },
});
