/**
 * ====================================
 * Allowed redirect URIs for cosmediate auth client apps
 * ====================================
 */
export const ALLOWED_REDIRECT_URIS = [
  { S: "http://localhost:3000/auth/processing" },
  { S: "http://localhost:3001/auth/processing" },
  { S: "http://localhost:3002/auth/processing" },
  { S: "http://localhost:3003/auth/processing" },
  { S: "https://cosmediate.com/auth/processing" },
  { S: "https://www.cosmediate.com/auth/processing" },
  { S: "https://blog.cosmediate.com/auth/processing" },
  { S: "https://auth.cosmediate.com/auth/processing" },
  { S: "https://app.cosmediate.com/auth/processing" },
  { S: "https://cosmediate.nl/auth/processing" },
  { S: "https://www.cosmediate.nl/auth/processing" },
  { S: "https://blog.cosmediate.nl/auth/processing" },
  { S: "https://app.cosmediate.nl/auth/processing" },
  { S: "https://cosmediate.be/auth/processing" },
  { S: "https://www.cosmediate.be/auth/processing" },
  { S: "https://blog.cosmediate.be/auth/processing" },
  { S: "https://app.cosmediate.be/auth/processing" },
  { S: "https://cosmediate.de/auth/processing" },
  { S: "https://www.cosmediate.de/auth/processing" },
  { S: "https://blog.cosmediate.de/auth/processing" },
  { S: "https://app.cosmediate.de/auth/processing" },
  { S: "https://cosmediate.fr/auth/processing" },
  { S: "https://www.cosmediate.fr/auth/processing" },
  { S: "https://blog.cosmediate.fr/auth/processing" },
  { S: "https://app.cosmediate.fr/auth/processing" },
  { S: "https://cosmediate.gr/auth/processing" },
  { S: "https://www.cosmediate.gr/auth/processing" },
  { S: "https://blog.cosmediate.gr/auth/processing" },
  { S: "https://app.cosmediate.gr/auth/processing" },
  { S: "https://cosmediate.it/auth/processing" },
  { S: "https://www.cosmediate.it/auth/processing" },
  { S: "https://blog.cosmediate.it/auth/processing" },
  { S: "https://app.cosmediate.it/auth/processing" },
  { S: "https://dev.cosmediate.com/auth/processing" },
  { S: "https://dev.blog.cosmediate.com/auth/processing" },
  { S: "https://dev.auth.cosmediate.com/auth/processing" },
  { S: "https://dev.app.cosmediate.com/auth/processing" },
  { S: "https://dev.cosmediate.nl/auth/processing" },
  { S: "https://dev.blog.cosmediate.nl/auth/processing" },
  { S: "https://dev.app.cosmediate.nl/auth/processing" },
  { S: "https://dev.cosmediate.be/auth/processing" },
  { S: "https://dev.blog.cosmediate.be/auth/processing" },
  { S: "https://dev.app.cosmediate.be/auth/processing" },
  { S: "https://dev.cosmediate.de/auth/processing" },
  { S: "https://dev.blog.cosmediate.de/auth/processing" },
  { S: "https://dev.app.cosmediate.de/auth/processing" },
  { S: "https://dev.cosmediate.fr/auth/processing" },
  { S: "https://dev.blog.cosmediate.fr/auth/processing" },
  { S: "https://dev.app.cosmediate.fr/auth/processing" },
  { S: "https://dev.cosmediate.gr/auth/processing" },
  { S: "https://dev.blog.cosmediate.gr/auth/processing" },
  { S: "https://dev.app.cosmediate.gr/auth/processing" },
  { S: "https://dev.cosmediate.it/auth/processing" },
  { S: "https://dev.blog.cosmediate.it/auth/processing" },
  { S: "https://dev.app.cosmediate.it/auth/processing" },
];
