import {
  text,
  textAC,
  kw,
  kwNorm,
  blobOff,
  geoPoint,
  Boolean,
  Integer,
  Float,
} from "../types.mjs";
import { indexSettings } from "../settings.mjs";

export const buildClinicMapping = (baseProps) => ({
  settings: indexSettings(),
  mappings: {
    dynamic: "strict",
    properties: {
      ...baseProps,
      logo: kw(),
      name: textAC(),
      images: kw(),
      faqs: {
        type: "nested",
        properties: { question: text(), answer: blobOff() },
      },
      overview: text(),
      tags: kwNorm(),
      clinicAge: kw(),
      clinicType: kw(),
      categories: {
        type: "nested",
        properties: { id: kw(), name: text() },
      },
      categoryIds: kw(),
      brandIds: kw(),
      treatmentCategoryIds: kw(),
      treatmentIds: kw(),
      clinicTreatmentIds: kw(),
      clinicSpecialistTreatmentIds: kw(),
      country: textAC(),
      state: textAC(),
      city: textAC(),
      postalCode: kw(),
      completeAddress: text(),
      location: geoPoint(),
      workingHours: {
        type: "nested",
        properties: {
          weekDay: kw(),
          available: Boolean(),
          startTime: { type: "date", format: "HH:mm" },
          endTime: { type: "date", format: "HH:mm" },
        },
      },
      email: kwNorm(),
      phone: kw(),
      website: kwNorm(),
      instagramId: kwNorm(),
      certificates: {
        type: "nested",
        properties: {
          certificateImage: {
            type: "keyword",
            index: false,
            doc_values: false,
          },
          name: text(),
          number: kw(),
          issueDate: { type: "date" },
          validTill: { type: "date" },
          email: kwNorm(),
          certificateHolderFirstName: text(),
          certificateHolderLastName: text(),
        },
      },
      available: Boolean(),
      status: kw(),
      parentClinicId: kw(),
      specialistIds: kw(),
      managerIds: kw(),
      role: kw(),
      leadId: kw(),
      searchClicks: Integer(),
      treatmentCount: Integer(),
      clinicTreatmentCount: Integer(),
      managerCount: Integer(),
      specialistCount: Integer(),
      avgPrice: Float(),
      minPrice: Float(),
      maxPrice: Float(),
      ratingSum: Float(),
      avgRating: Float(),
      reviewCount: Integer(),
    },
  },
});
