import {
  textAC,
  kw,
  kwNorm,
  geoPoint,
  Boolean,
  Integer,
  Float,
  text,
  blobOff,
} from "../types.mjs";
import { indexSettings } from "../settings.mjs";

export const buildSpecialistMapping = (baseProps) => ({
  settings: indexSettings(),
  mappings: {
    dynamic: "strict",
    properties: {
      ...baseProps,
      image: kw(),
      firstName: textAC(),
      lastName: textAC(),
      fullName: textAC(),
      age: Integer(),
      gender: kw(),
      totalExperience: Integer(),
      faqs: {
        type: "nested",
        properties: { question: text(), answer: blobOff() },
      },
      overview: text(),
      tags: kwNorm(),
      workingHours: {
        type: "nested",
        properties: {
          weekDay: kw(),
          available: Boolean(),
          startTime: { type: "date", format: "HH:mm" },
          endTime: { type: "date", format: "HH:mm" },
        },
      },
      certificates: {
        type: "nested",
        properties: {
          certificateImage: { type: "keyword", index: false, doc_values: false },
          name: text(),
          number: kw(),
          issueDate: { type: "date" },
          validTill: { type: "date" },
          email: kwNorm(),
          certificateHolderFirstName: text(),
          certificateHolderLastName: text(),
        },
      },
      clinicIds: kw(),
      parentClinicId: kw(),
      workingType: kw(),
      brandIds: kw(),
      treatmentCategoryIds: kw(),
      treatmentIds: kw(),
      clinicSpecialistTreatmentIds: kw(),
      phone: kw(),
      email: kwNorm(),
      instagramId: kwNorm(),
      website: kwNorm(),
      country: textAC(),
      state: textAC(),
      city: textAC(),
      postalCode: kw(),
      completeAddress: text(),
      location: geoPoint(),
      role: kw(),
      perms: kw(),
      status: kw(),
      defaultPasswordUsed: Boolean(),
      passwordSet: Boolean(),
      linkedProviders: kw(),
      available: Boolean(),
      leadId: kw(),
      searchClicks: Integer(),
      treatmentCount: Integer(),
      avgPrice: Float(),
      minPrice: Float(),
      maxPrice: Float(),
      ratingSum: Float(),
      avgRating: Float(),
      reviewCount: Integer(),
      clinicCount: Integer(),
    },
  },
});
