/**
 * CRUD-style actions recorded on target entities (admin, clinic, patient, etc.).
 */
export const ACTIVITY_MONITORING_ACTION = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  SOFT_DELETE: "SOFT_DELETE",
  REGISTER: "REGISTER",
  TREATMENT_SELECTION: "TREATMENT_SELECTION",
  PASSWORD_UPDATE: "PASSWORD_UPDATE",
  PASSWORD_SET: "PASSWORD_SET",
  LINK_OAUTH_PROVIDER: "LINK_OAUTH_PROVIDER",
  SIGN_IN: "SIGN_IN",
};
