export const AUDIT_LOG_ACTION = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  TREATMENT_SELECTION: "TREATMENT_SELECTION",
  PASSWORD_UPDATE: "PASSWORD_UPDATE",
  PASSWORD_SET: "PASSWORD_SET",
  LINK_OAUTH_PROVIDER: "LINK_OAUTH_PROVIDER",
  REGISTER: "REGISTER",
  SIGN_IN: "SIGN_IN",
};
